export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const GET_SUBJECT_REGIS_STD = 'student/GET_SUBJECT_REGIS_STD'
export const SET_SUBJECT_REGIS_STD = 'student/SET_SUBJECT_REGIS_STD'
export const REGISTER_SUBJECT_REQUEST = 'student/REGISTER_SUBJECT_REQUEST'
export const REGISTER_SUBJECT_REQUEST_SUCCESS = 'student/REGISTER_SUBJECT_REQUEST_SUCCESS'
export const REGISTER_SUBJECT_REQUEST_FAILED = 'student/REGISTER_SUBJECT_REQUEST_FAILED'