export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT = 'LOGOUT'

export const GET_CURRENT_YEAR = 'GET_CURRENT_YEAR'
export const SET_CURRENT_YEAR = 'SET_CURRENT_YEAR'

export const REQUEST_ERROR = 'REQUEST_ERROR'

export const GET_SUBJECT_REGIS_STD = 'student/GET_SUBJECT_REGIS_STD'
export const SET_SUBJECT_REGIS_STD = 'student/SET_SUBJECT_REGIS_STD'
export const REGISTER_SUBJECT_REQUEST = 'student/REGISTER_SUBJECT_REQUEST'
export const REGISTER_SUBJECT_REQUEST_SUCCESS = 'student/REGISTER_SUBJECT_REQUEST_SUCCESS'
export const REGISTER_SUBJECT_REQUEST_FAILED = 'student/REGISTER_SUBJECT_REQUEST_FAILED'
export const GET_SUBJECT_REGISTRATION = 'student/GET_SUBJECT_REGISTRATION'
export const SET_SUBJECT_REGISTRATION = 'student/SET_SUBJECT_REGISTRATION'


export const GET_STUDENT_APPROVE = 'lecturer/GET_STUDENT_APPROVE'
export const SET_STUDENT_APPROVE = 'lecturer/SET_STUDENT_APPROVE'
export const GET_SUBJECT_TEACH = 'lecturer/GET_SUBJECT_TEACH'
export const SET_SUBJECT_TEACH = 'lecturer/SET_SUBJECT_TEACH'
export const CREATE_SUBJECT = 'lecturer/CREATE_SUBJECT'
export const CREATE_SUBJECT_SUCCESS = 'lecturer/CREATE_SUBJECT_SUCCESS'
export const CREATE_SUBJECT_FAILED = 'lecturer/CREATE_SUBJECT_FAILED'
export const APPROVE_STUDENT = 'lecturer/APPROVE_STUDENT'
export const APPROVE_STUDENT_SUCCESS = 'lecturer/APPROVE_STUDENT_SUCCESS'
export const REJECT_STUDENT = 'lecturer/REJECT_STUDENT'
export const REJECT_STUDENT_SUCCESS = 'lecturer/REJECT_STUDENT_SUCCESS'
export const GET_SUBJECT_OPEN_SECTION = 'lecturer/GET_SUBJECT_OPEN_SECTION'
export const SET_SUBJECT_OPEN_SECTION = 'lecturer/SET_SUBJECT_OPEN_SECTION'
export const OPEN_SECTION = 'lecturer/OPEN_SECTION'
export const OPEN_SECTION_SUCCESS = 'lecturer/OPEN_SECTION_SUCCESS'
export const OPEN_SECTION_FAILED = 'lecturer/OPEN_SECTION_FAILED'
export const GET_ALL_BEACON = 'lecturer/GET_ALL_BEACON'
export const SET_ALL_BEACON = 'lecturer/SET_ALL_BEACON'

export const REGISTER_BEACON = 'lecturer/REGISTER_BEACON'
export const REGISTER_BEACON_SUCCESS = 'lecturer/REGISTER_BEACON_SUCCESS'
export const REGISTER_BEACON_FAILURE = 'lecturer/REGISTER_BEACON_FAILURE'




